-- -- auto install packer if not installed
-- local ensure_packer = function()
--   local fn = vim.fn
--   local install_path = fn.stdpath("data") .. "/site/pack/packer/start/packer.nvim"
--   if fn.empty(fn.glob(install_path)) > 0 then
--     fn.system({ "git", "clone", "--depth", "1", "https://github.com/wbthomason/packer.nvim", install_path })
--     vim.cmd([[packadd packer.nvim]])
--     return true
--   end
--   return false
-- end
-- local packer_bootstrap = ensure_packer() -- true if packer was just installed
--
-- -- autocommand that reloads neovim and installs/updates/removes plugins
-- -- when file is saved
-- vim.cmd([[
--   augroup packer_user_config
--     autocmd!
--     autocmd BufWritePost plugins-setup.lua source <afile> | PackerSync
--   augroup end
-- ]])
--
-- local status, packer = pcall(require, "packer")
-- if not status then
--   return
-- end
--
-- return packer.startup(function(use)
--   use("wbthomason/packer.nvim")
--   use("nvim-lua/plenary.nvim")
--   use("bluz71/vim-nightfly-guicolors") -- preferred colorscheme
--   use("EdenEast/nightfox.nvim") -- theme
--   use('projekt0n/github-nvim-theme') -- theme
--   use('bluz71/vim-moonfly-colors') -- theme
--   use("tpope/vim-surround")
--   use("vim-scripts/ReplaceWithRegister")
--   use("numToStr/Comment.nvim")
--   use("nvim-tree/nvim-tree.lua")
--   use("nvim-tree/nvim-web-devicons")
--   use("nvim-lualine/lualine.nvim")
--
--   -- fuzzy finding w/ telescope
--   use({ "nvim-telescope/telescope-fzf-native.nvim", run = "make" }) -- dependency for better sorting performance
--   use({ "nvim-telescope/telescope.nvim", branch = "0.1.x" }) -- fuzzy finder
--
--   -- dashboard
--   use({
--     'nvimdev/dashboard-nvim',
--     event = 'VimEnter',
--     requires = {'nvim-tree/nvim-dev-devicons'},
--   })
--
--   -- autocompletion
--   use({
--     "hrsh7th/nvim-cmp",
--     dependencies = {
--     "hrsh7th/cmp-nvim-lsp",
--     "L3MON4D3/LuaSnip",
--     "saadparwaiz1/cmp_luasnip",
--     "rafamadriz/friendly-snippets",
--     "hrsh7th/cmp-buffer", -- source for text in buffer
--     "hrsh7th/cmp-path", -- source for file system paths
--     },
--   }) -- completion plugin
--
--   use("hrsh7th/cmp-buffer") -- source for text in buffer
--   use("hrsh7th/cmp-path") -- source for file system paths
--
--    -- snippets
--   use("L3MON4D3/LuaSnip") -- snippet engine
--   use("saadparwaiz1/cmp_luasnip") -- for autocompletion
--   use("rafamadriz/friendly-snippets") -- useful snippets
--
--   -- managing & installing lsp servers
--   use("williamboman/mason.nvim")
--   use("williamboman/mason-lspconfig.nvim") -- bridges gap b/w mason & lspconfig
--
--   -- configuring lsp servers
--   use("neovim/nvim-lspconfig") -- easily configure language servers
--   use("hrsh7th/cmp-nvim-lsp") -- for autocompletion
--   use({
--     "nvimdev/lspsaga.nvim",
--     after = 'nvim-lspconfig',
--   }) -- enhanced lsp uis
--
--   use("onsails/lspkind.nvim")
--
--   -- formatting & linting
--   use("jose-elias-alvarez/null-ls.nvim")
--   use("jayp0521/mason-null-ls.nvim")
--
--   -- treesitter configuration
--   use({
--     "nvim-treesitter/nvim-treesitter",
--     run = function()
--       local ts_update = require("nvim-treesitter.install").update({ with_sync = true })
--       ts_update()
--     end,
--   })
--
--   -- semantic highlighting
--   use("m-demare/hlargs.nvim")
--
--    -- auto closing
--   use("vimjas/vim-python-pep8-indent") -- autoclose parens, brackets, quotes, etc...
--   use({ "windwp/nvim-ts-autotag", after = "nvim-treesitter" }) -- autoclose tags
--   use('echasnovski/mini.nvim') -- actually autocloses brackets...
--
--   use("lukas-reineke/indent-blankline.nvim")
--   use('romgrk/barbar.nvim')
--
--   use("theprimeagen/harpoon")
--
--   -- highlight words
--   use("RRethy/vim-illuminate")
--
--   -- yank highlighting
--   use("machakann/vim-highlightedyank")
--
--   -- popup menu mod
--   use("MunifTanjim/nui.nvim")
--   use({
--   "folke/noice.nvim",
--   opts = {
--     -- add any options here
--   },
--   dependencies = {
--     -- if you lazy-load any plugin below, make sure to add proper `module="..."` entries
--     "MunifTanjim/nui.nvim",
--     -- OPTIONAL:
--     --   `nvim-notify` is only needed, if you want to use the notification view.
--     --   If not available, we use `mini` as the fallback
--     -- "rcarriga/nvim-notify",
--     }
--   }
-- )
--
--   if packer_bootstrap then
--     require("packer").sync()
--     end
-- end)
--
